#!/usr/bin/env bash

sudo_available() {
  command -v sudo >/dev/null 2>&1 || return 1
  sudo -n true >/dev/null 2>&1 && return 0
  [ -t 0 ] || return 1
  sudo -v
}

server_has_sudo() {
  case "${SERVER_HAS_SUDO:-}" in
    true) return 0 ;;
    false) return 1 ;;
    *) sudo_available ;;
  esac
}

git_global_proxy() {
  git config --global --get http.proxy 2>/dev/null || true
}

_tabby_proxy_endpoint() {
  local proxy_url="$1"
  local endpoint_script

  endpoint_script="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/proxy_endpoint.py"
  printf '%s\n' "$proxy_url" | python3 "$endpoint_script" -
}

_tabby_normalize_proxy_candidate() {
  local proxy_url="$1"
  local endpoint host port url_host

  endpoint="$(_tabby_proxy_endpoint "$proxy_url")" || return 1
  IFS=$'\t' read -r host port <<<"$endpoint"
  case "$host" in
    *:*) url_host="[$host]" ;;
    *) url_host="$host" ;;
  esac
  printf 'http://%s:%s\n' "$url_host" "$port"
}

_tabby_valid_port() {
  case "$1" in
    ''|*[!0-9]*) return 1 ;;
  esac
  [ "$1" -ge 1 ] && [ "$1" -le 65535 ]
}

_tabby_clash_mixed_port() {
  local environment_file="$HOME/tools/clash-for-linux/.env"
  local port

  [ -r "$environment_file" ] || return 1
  port="$(sed -n -E "s/^[[:space:]]*(export[[:space:]]+)?MIXED_PORT[[:space:]]*=[[:space:]]*['\"]?([0-9]+)['\"]?[[:space:]]*(#.*)?$/\2/p" "$environment_file" | sed -n '1p')"
  _tabby_valid_port "$port" || return 1
  printf '%s\n' "$port"
}

detect_proxy_candidate() {
  local candidate normalized port

  for candidate in "${http_proxy:-}" "${https_proxy:-}" "${all_proxy:-}" \
    "${HTTP_PROXY:-}" "${HTTPS_PROXY:-}" "${ALL_PROXY:-}"; do
    normalized="$(_tabby_normalize_proxy_candidate "$candidate" 2>/dev/null)" && {
      printf '%s\n' "$normalized"
      return 0
    }
  done

  candidate="$(git_global_proxy)"
  if normalized="$(_tabby_normalize_proxy_candidate "$candidate" 2>/dev/null)"; then
    printf '%s\n' "$normalized"
    return 0
  fi

  if port="$(_tabby_clash_mixed_port)"; then
    candidate="http://127.0.0.1:${port}"
    if normalized="$(_tabby_normalize_proxy_candidate "$candidate" 2>/dev/null)"; then
      printf '%s\n' "$normalized"
      return 0
    fi
  fi

  printf '%s\n' 'http://127.0.0.1:7890'
}

render_proxy_aliases() {
  local host="$1"
  local port="$2"
  local url_host="$host"
  local nc_host="$host"

  [[ "$host" =~ ^[A-Za-z0-9._:-]+$ ]] || return 1
  _tabby_valid_port "$port" || return 1
  case "$host" in
    *:*)
      url_host="[$host]"
      nc_host="[$host]"
      ;;
  esac

  cat <<EOF
# Generated by tabby-config. Edit the installer input instead of this file.
_tabby_proxy_on() {
  export http_proxy="http://${url_host}:${port}"
  export https_proxy="http://${url_host}:${port}"
  export HTTP_PROXY="http://${url_host}:${port}"
  export HTTPS_PROXY="http://${url_host}:${port}"
  export all_proxy="socks5://${url_host}:${port}"
  export ALL_PROXY="socks5://${url_host}:${port}"
  export no_proxy="localhost,127.0.0.1,::1"
  export NO_PROXY="localhost,127.0.0.1,::1"
  if command -v nc >/dev/null 2>&1; then
    export GIT_SSH_COMMAND="ssh -o ProxyCommand='nc -X 5 -x ${nc_host}:${port} %h %p'"
  else
    unset GIT_SSH_COMMAND
    printf '%s\n' 'WARN: netcat-openbsd (nc) is required for Git SSH proxy support' >&2
  fi
}

_tabby_proxy_off() {
  unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY no_proxy NO_PROXY GIT_SSH_COMMAND
}

alias proxyon='_tabby_proxy_on'
alias proxyoff='_tabby_proxy_off'
EOF
}

_tabby_write_atomic() {
  local target="$1"
  local content="$2"
  local directory temporary status

  directory="$(dirname "$target")"
  mkdir -p "$directory"
  status=$?
  [ "$status" -eq 0 ] || return "$status"
  temporary="$(mktemp "$directory/.${target##*/}.XXXXXX")"
  status=$?
  [ "$status" -eq 0 ] || return "$status"
  printf '%s\n' "$content" >"$temporary"
  status=$?
  if [ "$status" -ne 0 ]; then
    rm -f "$temporary" || true
    return "$status"
  fi
  mv "$temporary" "$target"
}

_tabby_server_environment_content() {
  local conda_enabled="$1"
  local rootless_enabled="$2"

  cat <<'EOF'
# Generated by tabby-config. This file is safe to source from Bash and Zsh.
_tabby_server_env_source="${XDG_CONFIG_HOME:-$HOME/.config}/tabby-config/proxy-aliases.sh"
if [ -r "$_tabby_server_env_source" ]; then
  . "$_tabby_server_env_source"
fi
unset _tabby_server_env_source
EOF

  if [ "$conda_enabled" = true ]; then
    cat <<'EOF'
if [ -d "$HOME/miniforge3/condabin" ]; then
  case ":$PATH:" in
    *":$HOME/miniforge3/condabin:"*) ;;
    *) PATH="$HOME/miniforge3/condabin:$PATH" ;;
  esac
fi
EOF
  else
    printf '%s\n' '# conda integration disabled'
  fi

  if [ "$rootless_enabled" = true ]; then
    cat <<'EOF'
if [ -d "$HOME/bin" ]; then
  case ":$PATH:" in
    *":$HOME/bin:"*) ;;
    *) PATH="$HOME/bin:$PATH" ;;
  esac
fi
export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock
EOF
  else
    printf '%s\n' '# rootless Docker integration disabled'
  fi
}

write_server_shell_environment() {
  local proxy_url="$1"
  local conda_enabled="$2"
  local rootless_enabled="$3"
  local environment_dir endpoint host port aliases server_environment source_block common_path status

  endpoint="$(_tabby_proxy_endpoint "$proxy_url")"
  status=$?
  [ "$status" -eq 0 ] || return "$status"
  IFS=$'\t' read -r host port <<<"$endpoint"
  status=$?
  [ "$status" -eq 0 ] || return "$status"
  aliases="$(render_proxy_aliases "$host" "$port")"
  status=$?
  [ "$status" -eq 0 ] || return "$status"

  environment_dir="${XDG_CONFIG_HOME:-$HOME/.config}/tabby-config"
  _tabby_write_atomic "$environment_dir/proxy-aliases.sh" "$aliases"
  status=$?
  [ "$status" -eq 0 ] || return "$status"
  server_environment="$(_tabby_server_environment_content "$conda_enabled" "$rootless_enabled")"
  status=$?
  [ "$status" -eq 0 ] || return "$status"
  _tabby_write_atomic "$environment_dir/server-env.sh" "$server_environment"
  status=$?
  [ "$status" -eq 0 ] || return "$status"

  if ! declare -F upsert_managed_block >/dev/null 2>&1; then
    common_path="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/common.sh"
    status=$?
    [ "$status" -eq 0 ] || return "$status"
    # shellcheck source=bootstrap/common.sh
    source "$common_path"
    status=$?
    [ "$status" -eq 0 ] || return "$status"
  fi
  source_block='[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/tabby-config/server-env.sh" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/tabby-config/server-env.sh"'
  upsert_managed_block "$HOME/.bashrc" server-environment "$source_block"
}
